---
cops_dbsmartbackup_confs:
  db:
    conf_path: /srv/backups/db.conf
    keep_lasts: 1
    type: mysql
    keep_days: 2
    keep_logs: 7
    _periodicity: "0 3 * * *"
    free_form: |
      export HOST="{{cops_wordpress_db_host}}"
      export PORT="{{cops_wordpress_db_port}}"
      export DBNAMES="{{cops_wordpress_db_name}}"
      export PASSWORD="{{cops_wordpress_db_password}}"
      export DBUSER="{{cops_wordpress_db_user}}"
      export RUNAS=""
