---
cops_wordpress_name: wordpressinstance
cops_wordpress_project_module_name: "{{cops_wordpress_name}}"
cops_wordpress_settings_module: "{{cops_wordpress_project_module_name}}.settings.instances.{{cops_wordpress_deploy_env}}"
cops_wordpress_py_ver: "3.7"
cops_wordpress_deploy_env: "dev"
cops_wordpress_docker_image_tag: "{{cops_wordpress_name}}"
cops_wordpress_default_docker_tag: "latest"
cops_wordpress_docker_tag: "{{cops_wordpress_default_docker_tag}}"
cops_wordpress_tld_domain: example.com
cops_wordpress_mail_domain: "{{ cops_wordpress_tld_domain }}"
cops_wordpress_default_gitref: "master"
cops_wordpress_gitref: "{{cops_wordpress_default_gitref}}"
cops_wordpress_dir: "/srv/docker/{{cops_wordpress_name}}"
cops_wordpress_hostname: "{{cops_wordpress_deploy_env}}-{{cops_wordpress_name}}.{{cops_wordpress_tld_domain}}"
cops_wordpress_alternate_hostnames: [".{{cops_wordpress_tld_domain}}"]
cops_wordpress_secret_key: "SuperSecret"
cops_wordpress_gateway: "{{ ansible_default_ipv4.address}}"
cops_wordpress_composename: "{{cops_wordpress_name}}"
cops_wordpress_db_host: "db"
cops_wordpress_db_prefix: "3306"
cops_wordpress_db_port: "3306"
cops_wordpress_db_user: "wp"
cops_wordpress_db_password: "secret4gzQNe3c8851VOJ"
cops_wordpress_db_root_password: "{{cops_wordpress_db_password}}"
cops_wordpress_db_name: "{{cops_wordpress_name}}"
cops_wordpress_devmode: False
cops_wordpress_build_args: "--no-cache wordpress cron"
# backup could be remove in a-while when we have redeployed it everywhere
cops_wordpress_restarted_services_default: "db redis wordpress backup cron"
cops_wordpress_restarted_services: "{{cops_wordpress_restarted_services_default}}"
cops_wordpress_purge_volumes: [statics]
cops_wordpress_sshargs: >-
  {% set k = hostvars[inventory_hostname].get(
                'ansible_ssh_private_key_file', '') %}
  {% if k%}-o IdentityFile={{k}} -o IdentitiesOnly=yes{%endif%}
  {% if (
      hostvars[inventory_hostname].ansible_connection|default('ssh')
     ) not in [ 'smart', 'local'] %}
  {{ hostvars[inventory_hostname].ssh_args | default('') }}
  {{ hostvars[inventory_hostname].ansible_ssh_args | default('') }}
  {{ hostvars[inventory_hostname].ansible_ssh_common_args | default('') }}
  {{ hostvars[inventory_hostname].ansible_ssh_extra_args | default('') }}
  {% endif %}
cops_wordpress_build: false
cops_wordpress_pull: true
cops_wordpress_registries: []
#- {registry: registry.foo.net, username: foo, password: bar}
cops_wordpress_compose_files: [docker-compose.yml, docker-compose-prod.yml]
cops_wordpress_dc:
  docker-compose {% for i in cops_wordpress_compose_files %} -f {{i}}{% endfor %}
  -p "{{cops_wordpress_composename}}"
cops_wordpress_mailcatcher_user: mailcatcher
cops_wordpress_mailcatcher_password: mailcatcher
cops_wordpress_email_server: mailcatcher
cops_wordpress_email_host_port: 1025
cops_wordpress_hosts_whitelist: "{{(
    [cops_wordpress_hostname, '0.0.0.0', '.{0}'.format(cops_wordpress_hostname)]+
    cops_wordpress_alternate_hostnames
  )|join('-|_')}}"
cops_wordpress_sentry_tags: ["env:{{cops_wordpress_deploy_env}}"]
cops_wordpress_step_rsync: true
cops_wordpress_sentry_dsn: ''
cops_wordpress_db_charset: 'utf8'
cops_wordpress_db_collate: ''
cops_wordpress_sentry_error_types: "E_ALL & ~E_DEPRECATED & ~E_NOTICE & ~E_USER_DEPRECATED"
cops_wordpress_http_protect_user: "root"
cops_wordpress_http_protect_password: "rootroot"
cops_wordpress_docker_env_freeform: |-
  {{ cops_wordpress_docker_env_defaults}}
  {{ cops_wordpress_docker_env_extra}}
cops_wordpress_logrotate: "365"
cops_wordpress_admin_allowed_ips: []
cops_wordpress_remote_ips: []
cops_wordpress_login_url: "wp-login.php"
cops_wordpress_docker_env_defaults: |-
  WORDPRESS_LOGIN_URL={{cops_wordpress_login_url}}
  WORDPRESS_REMOTE_IPS={{cops_wordpress_remote_ips|join("-|_")}}
  WORDPRESS_LOGROTATE={{cops_wordpress_logrotate}}
  WORDPRESS_ALLOWED_ADMIN_IPS={{cops_wordpress_admin_allowed_ips|join("-|_")}}
  MYSQL_HOST={{cops_wordpress_db_host}}
  MYSQL_PORT={{cops_wordpress_db_port}}
  MYSQL_DATABASE={{cops_wordpress_db_name}}
  MYSQL_USER={{cops_wordpress_db_user}}
  MYSQL_PASSWORD={{cops_wordpress_db_password}}
  MYSQL_ROOT_PASSWORD={{cops_wordpress_db_root_password}}
  WORDPRESS_DB_HOST={{cops_wordpress_db_host}}
  WORDPRESS_DB_PORT={{cops_wordpress_db_port}}
  WORDPRESS_DB_USER={{cops_wordpress_db_user}}
  WORDPRESS_DB_CHARSET={{cops_wordpress_db_charset}}
  WORDPRESS_DB_COLLATE={{cops_wordpress_db_collate}}
  WORDPRESS_DB_PASSWORD={{cops_wordpress_db_password}}
  WORDPRESS_DB_NAME={{cops_wordpress_db_name}}
  WORDPRESS_TABLE_PREFIX={{cops_wordpress_db_prefix}}
  WORDPRESS__DEPLOY_ENV={{cops_wordpress_deploy_env}}
  WORDPRESS__HTTP_PROTECT_USER={{cops_wordpress_http_protect_user}}
  WORDPRESS__HTTP_PROTECT_PASSWORD={{cops_wordpress_http_protect_password}}
  {% if cops_wordpress_devmode %}
  WORDPRESS_DEBUG=y
  {% endif %}
  MAILCATCHER_USER={{cops_wordpress_mailcatcher_user}}
  MAILCATCHER_PASSWORD={{cops_wordpress_mailcatcher_password}}
# free form for params inside dockerenv
cops_wordpress_dotenv: |-
  APP_TYPE=wordpress
  WORDPRESS_PY_VER={{ cops_wordpress_py_ver }}
  WORDPRESS_NAME={{ cops_wordpress_name }}
  COMPOSE_PROJECT_NAME={{cops_wordpress_composename}}
  CONTROL_COMPOSE_FILES={{cops_wordpress_compose_files|join(' ')}}
  CI_COMMIT_SHA={{cops_wordpress_gitref}}
  WORDPRESS_IMAGE={{ cops_wordpress_docker_image }}
  WORDPRESS_IMAGE_VERSION={{cops_wordpress_docker_tag}}
  {% if cops_wordpress_sentry_dsn %}
  WORDPRESS__SENTRY_DSN={{cops_wordpress_sentry_dsn}}
  WORDPRESS__SENTRY_ERROR_TYPES={{cops_wordpress_sentry_error_types}}
  WORDPRESS__SENTRY_VERSION={{cops_wordpress_sentry_version}}
  WORDPRESS__SENTRY_ENV={{cops_wordpress_sentry_env}}
  {% endif %}
  WORDPRESS_AUTH_KEY{{cops_wordpress_auth_key}}
  WORDPRESS_SECURE_AUTH_KEY={{cops_wordpress_secure_auth_key}}
  WORDPRESS_LOGGED_IN_KEY={{cops_wordpress_logged_in_key}}
  WORDPRESS_NONCE_KEY=z{{cops_wordpress_nonce_key}}
  WORDPRESS_AUTH_SALT={{cops_wordpress_auth_salt}}
  WORDPRESS_SECURE_AUTH_SALT={{cops_wordpress_secure_auth_salt}}
  WORDPRESS_LOGGED_IN_SALT={{cops_wordpress_logged_in_salt}}
  # default to unique random SHA1s
  WORDPRESS_NONCE_SALT={{cops_wordpress_nonce_salt}}
cops_wordpress_sentry_version: "{{cops_wordpress_docker_tag}}"
cops_wordpress_sentry_env: "{{cops_wordpress_deploy_env}}"
cops_wordpress_dotenv_extra: ""
# free form for params inside dockerenv
cops_wordpress_docker_env_extra: ""
# free form for params inside local.php
cops_wordpress_localphp_extra:  ""

# Normally playbook is in ./.ansible/playbooks
cops_wordpress_code_dir: "{{playbook_dir}}/../.."
cops_wordpress_code_rsync_opts: [
    "-azv",
    # include deploy projects base code
    "--include", "local/*-deploy",
    "--exclude", ".ansible",
    "--exclude", "local/*",
    "--exclude", ".git",
    "--exclude", ".tox",
    "--exclude", ".env",
    "--exclude", "docker.env"]
cops_wordpress_mysql_startup_timeout: 45s
